// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "018f1fd0-a782-4174-a75a-9963c75e33fa";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onESP322MTVChange();
void onESP322PWRChange();

int ESP32_2_MTV;
bool ESP32_2_Motion;
bool ESP32_2_PWR;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(ESP32_2_MTV, READWRITE, ON_CHANGE, onESP322MTVChange);
  ArduinoCloud.addProperty(ESP32_2_Motion, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ESP32_2_PWR, READWRITE, ON_CHANGE, onESP322PWRChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
