// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "8c049ac7-8d0f-4f6e-8e00-17dd855c15bf";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onESP321LSVChange();
void onESP321PWRChange();

float ESP32_1_LSV;
bool ESP32_1_PWR;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(ESP32_1_LSV, READWRITE, ON_CHANGE, onESP321LSVChange);
  ArduinoCloud.addProperty(ESP32_1_PWR, READWRITE, ON_CHANGE, onESP321PWRChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
